version: "3.8"

services:
  postgres-db:
    image: postgres:14
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quarkus-social
    ports:
      - 5434:5432